fixed regex for rpc definition to allow use of .
vihangm/sublime-protobuf-syntax pull request #12
Opened 2017-07-09 17:29 UTC by jvsteiner

This is legal syntax which isn't highlighted correctly.  It occurs when using someone elses protobuf definitions, for example from a foreign.api package:

```
rpc MyServiceRoute(MyRequest) returns (foreign.api.Response) { // <- here
	option (google.api.http) = {
		post: "/v1/echo" body: "*"
	};
```

2017-07-10 23:10 UTC, vihangm commented
Can you update the `.YAML-tmLanguage` version of the file and then autogenerate the `.tmLanguage` with https://github.com/SublimeText/PackageDev

Otherwise these changes will get overwritten when someone else autogenerates the `.tmLaguage` from the YAML file.

2017-07-11 15:51 UTC, vihangm requested changes

2017-07-11 15:51 UTC, vihangm commented on Protobuf.tmLanguage
> +		</dict>
Did you mean to include these changes? This seems to be missing in the YAML.

2017-07-11 15:54 UTC, jvsteiner commented
I did not, those were merged later on my local copy

Vihang Mehta wrote:
>
> *@vihangm* requested changes on this pull request.
>
> ------------------------------------------------------------------------
>
> In Protobuf.tmLanguage
> <https://github.com/vihangm/sublime-protobuf-syntax/pull/12#discussion_r126731119>:
>
> > +			<key>captures</key>
> +			<dict>
> +				<key>1</key>
> +				<dict>
> +					<key>name</key>
> +					<string>keyword.source.proto</string>
> +				</dict>
> +				<key>2</key>
> +				<dict>
> +					<key>name</key>
> +					<string>entity.name.tag</string>
> +				</dict>
> +			</dict>
> +			<key>match</key>
> +			<string>(syntax)(?=(\s+=\s+)(["]?[A-Za-z][A-Za-z0-9-_.\/]*["]?)(;))</string>
> +		</dict>
>
> Did you mean to include these changes? This seems to be missing in the
> YAML.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/vihangm/sublime-protobuf-syntax/pull/12#pullrequestreview-49242679>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABHIEFBnLIyYw2UuNOEEy7keEl9SB8_2ks5sM5oMgaJpZM4OSIGX>.
>

2017-07-11 15:58 UTC, vihangm commented
Abandoning in favor of #13

2017-07-11 15:58 UTC, closed without merging